---
name: Go Checks

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      # go-version:
      #   description: "Go version to use"
      #   required: false
      #   default: "stable"
      #   type: string
      go-version-file:
        description: "Go version file to use"
        required: false
        default: "go.mod"
        type: string
      codeql-enable:
        description: "Whether to enable CodeQL job"
        required: false
        default: false
        type: boolean

jobs:
  quality-gate:
    permissions:
      contents: read
      pull-requests: read
      # checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6.0.0
        with:
          go-version-file: ${{ inputs.go-version-file }}
      - name: Lint files with golangci-lint
        id: golangci
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9  # v8.0.0
        with:
          version: latest
      - name: Test changes with go test
        id: go-test
        run: |
          go test -cover ./...
      - name: Format and print GH step summary
        if: always()
        run: |
          echo "| Key | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|:--|:--|" >> $GITHUB_STEP_SUMMARY
          echo "| **golangci-lint** | ${{ steps.golangci.outcome }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **go-test** | ${{ steps.go-test.outcome }} |" >> $GITHUB_STEP_SUMMARY

  codeql-analyze:
    permissions:
      contents: read
      security-events: write
      # only required for workflows in private repositories
      # actions: read
      # only required for internal or private CodeQL packs
      # packages: read
    needs: [quality-gate]
    if: ${{ inputs.codeql-enable }}
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: go
            build-mode: autobuild
    steps:
      - name: Checkout default branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: Initialize CodeQL
        uses: github/codeql-action/init@0499de31b99561a6d14a36a5f662c2a54f91beee  # v4.31.2
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v.6.0.0
        with:
          go-version-file: ${{ inputs.go-version-file }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@0499de31b99561a6d14a36a5f662c2a54f91beee  # v4.31.2
      # - name: Manual build steps
      #   if: matrix.build-mode == "manual"
      #   shell: bash
      #   run: |
      #    make build
      - name: Perform CodeQL Analysis
        id: analyze
        uses: github/codeql-action/analyze@0499de31b99561a6d14a36a5f662c2a54f91beee  # v4.31.2
        with:
          category: "/language:${{matrix.language}}"
      - name: Format and print GH step summary
        if: always()
        run: |
          echo "| Key | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|:--|:--|" >> $GITHUB_STEP_SUMMARY
          echo "| **codeql** | ${{ steps.analyze.outcome }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **codeql_verbosity** | $CODEQL_VERBOSITY  |" >> $GITHUB_STEP_SUMMARY
