---
name: Go Deploy

on:
  workflow_call:
    # TODO: Seems like 'goreleaser' does not support passing it by ENV.
    # inputs:
    #   goreleaser-config-filename:
    #     description: "Goreleaser config filename"
    #     required: false
    #     default: "configs/goreleaser.yaml"
    #     type: string

jobs:
  goreleaser:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 0
      # - name: Fetch tags
      #   run: |
      #     git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v.6.0.0
        with:
          go-version: "stable"
      - name: Build and release with goreleaser
        id: releaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a  # v6.4.0
        with:
          distribution: goreleaser
          version: latest
          args: "release --clean --config configs/goreleaser.yaml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Format and print GH step summary
        if: always()
        run: |
          echo "| Key | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|:--|:--|" >> $GITHUB_STEP_SUMMARY
          echo "| **goreleaser** | ${{ steps.releaser.outcome }} |" >> $GITHUB_STEP_SUMMARY
