---
name: SecOps

on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  trivy:
    permissions:
      contents: read
      security-events: write
      # only required for workflows in private repositories
      # actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: Run Trivy scanner in fs mode for vuln and secret
        id: trivy-scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8  # v0.33.1
        with:
          scan-type: "fs"
          scanners: "vuln,secret"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
      - name: Run Trivy scanner in fs mode for misconfig
        id: trivy-scan-misconfig
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8  # v0.33.1
        with:
          scan-type: "fs"
          scanners: "misconfig"
          ignore-unfixed: true
          format: "table"
          severity: "CRITICAL,HIGH"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@0499de31b99561a6d14a36a5f662c2a54f91beee  # v4.31.2
        with:
          sarif_file: "trivy-results.sarif"
      - name: Format and print GH step summary
        if: always()
        run: |
          echo "| Key | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|:--|:--|" >> $GITHUB_STEP_SUMMARY
          echo "| **trivy** | ${{ steps.trivy-scan.outcome }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **trivy_ignore_unfixed** | $TRIVY_IGNORE_UNFIXED  |" >> $GITHUB_STEP_SUMMARY
          echo "| **trivy_severity** | $TRIVY_SEVERITY  |" >> $GITHUB_STEP_SUMMARY
          echo "| **trivy_scanners** | $TRIVY_SCANNERS  |" >> $GITHUB_STEP_SUMMARY
